[project]
name = "call-me-maybe"
version = "0.1.0"
description = "Introduction to function calling in LLMs"
readme = "README.md"
authors = [
    { name = "katakada"}
]
requires-python = ">=3.10"
dependencies = []

[project.scripts]
call-me-maybe = "call_me_maybe:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
